# -*- coding: utf-8 -*-
"""Summarization for Kula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18C7ZUc4fWcFBtR1xDH6ntJhxGAJWCjrC

**HUGGING** **FACE**-TRANSFORMERS-SUMMARIZATION
"""

!pip install transformers

from transformers import pipeline

summarizer = pipeline("summarization")

Email = """I must say that I am not unfamiliar with what you are doing here, it is howthings have always been done. 
You(the board) just expect us to follow instructions and not have an opinion, even when you ask for it, it is just for the sake of asking. Unfortunately we thought it would be different this time.

And with all due respect, you don't really understand the struggle that I'm talking about because your NGO, Wellbody Alliance was never like WAMM.

Also, I have been in WAMM since 2009 and have been to all operational sites and the first time I heard your name was in 2014 when Gabe was about to go work for PIH.

And we were given the power to decide what we wanted to do with the funds, just look at the very first message in this chain that Gabriel sent. Eventhe title of the chain says it all, "na u" translates as "it is you". 
Yousay it is in our best interest, we showed you what we would like to happen in our best interest, the board voted on it and we clarified all Your
doubts, but you must have just tossed it aside as garbage and decided to give instructions instead because it would be best if we just do what we are told. 
But I would like to state here that no one told us what to do when we implemented the Building resilience project but it turned out okay.


For the sake of clarity and to avoid any future misunderstanding, it would be good to know who the mouth piece of the board is. Who will be the board's spokesperson from now on, because what Gabe said in the beginning and what is being said now are different things. """

summarizer(Email, max_length=130, min_length=30, do_sample=False)